branches:
  only:
    - master


os: Visual Studio 2017
version: "{branch}-{build}"

clone_folder: c:\projects\build

environment:
  BASH: C:\msys64\usr\bin\env MSYSTEM=MINGW64 C:\msys64\usr\bin\bash
  MYCI_BINTRAY_API_KEY:
    secure: t04W/09OyK0B8CxJHydCkay+Fm3i6KkBciVXjzk0u09v6F9wtDn/dsuqd5eMIj8s

install:
  - cmd: \%BASH% -lc "echo '[pacman]' >> /etc/pacman.conf"
  - cmd: "%BASH% -lc \"echo 'SigLevel = Optional TrustAll' >> /etc/pacman.conf\""
  - cmd: "%BASH% -lc \"echo 'Server = https://dl.bintray.com/igagis/msys2/mingw/$arch' >> /etc/pacman.conf\""
  - cmd: "%BASH% -lc \"pacman -Sy --noconfirm myci\""

before_build:


build_script:
  - cmd: "%BASH% -lc \"cd /c/projects/build/ && myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` msys2/PKGBUILD.in\""
  - cmd: "%BASH% -lc \"cd /c/projects/build/msys2 && makepkg --syncdeps --noconfirm --skipinteg\""

test_script:
  #pacman package build already performs tests

deploy_script:
  - cmd: if "%APPVEYOR_REPO_TAG%"=="true" (%BASH% -lc "cd /c/projects/build && myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw/x86_64 msys2/*.tar.xz") else (echo Skipping deploy because not a tagged commit.)
