include prorab.mk
include $(d)../../../src/prorab-doxygen.mk

this_out_dir := out
this_name := testdoc
#this_version := $(shell myci-deb-version.sh ../debian/changelog)

$(eval $(prorab-build-doxygen))
